branches:
  only:
    - test-branch-2
language: python
compiler:
  - gcc
python:
  - "2.6"
env:
  - NUPIC=$TRAVIS_BUILD_DIR

notifications:
  irc: 
    channels: 
      - "irc.freenode.net#nupic"
    use_notice: true
    skip_join: true
  webhooks: 
    urls:
      - http://issues.numenta.org:8081/travis
    on_start: true

before_install:
  - "source $NUPIC/env.sh"
install: "$NUPIC/build.sh"

# dummy tests for now
script: "pwd"

after_success:
  - "echo yay!"
